[project]
name = "wearable-xai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "ipykernel>=6.30.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "rich>=14.1.0",
    "rpy2>=3.6.1",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
]
