"""
Tests for the feature engineering module.
This module tests the feature extraction functions to ensure they correctly generate the expected features.
"""
import numpy as np
from src.engineered_features import create_features

def test_create_features_names():
    # Noisy sine wave with 10 cycles over 1024 samples.
    """
    Test that the correct feature names are generated by create_features.

    The correct feature names should be:
        - max_amp
        - sign_changes
        - mean_peak_width
        - mean_peak_prominence
        - post_peak_area
        - pre_peak_area

    This test checks that the generated feature names match this list.
    """
    signal = np.sin(np.linspace(0, 10 * np.pi, 1024)) + 0.1 * np.random.randn(1024)
    
    # Create overlapping windows (same logic as your pipeline uses)
    window_size = 256
    step_size = 128
    windows = [
        signal[i:i + window_size]
        for i in range(0, len(signal) - window_size + 1, step_size)
    ]

    # Generate features
    features = [create_features(window) for window in windows]

    # Feature names should match the expected features
    expected_features = [
        'max_amp', 'sign_changes', 'mean_peak_width', 'mean_peak_prominence', 'post_peak_area', 'pre_peak_area'
    ]
    assert list(features[0].keys()) == expected_features, "Feature names should match expected features"
    
def test_create_features_types():
    # Noisy sine wave with 10 cycles over 1024 samples.
    """
    Test that the correct feature values are generated by create_features.

    The correct feature values should be:
        - max_amp: float
        - sign_changes: int
        - mean_peak_width: float
        - mean_peak_prominence: float
        - post_peak_area: float
        - pre_peak_area: float

    This test checks that the generated feature values match this list.
    """
    signal = np.sin(np.linspace(0, 10 * np.pi, 1024)) + 0.1 * np.random.randn(1024)
    signal_features = create_features(signal)
    assert isinstance(signal_features, dict), "Features should be returned as a dictionary"
    assert 'max_amp' in signal_features, "max_amp feature should be present"
    assert 'sign_changes' in signal_features, "sign_changes feature should be present"
    assert 'mean_peak_width' in signal_features, "mean_peak_width feature should be present"
    assert 'mean_peak_prominence' in signal_features, "mean_peak_prominence feature should be present"
    assert 'post_peak_area' in signal_features, "post_peak_area feature should be present"
    assert 'pre_peak_area' in signal_features, "pre_peak_area feature should be present"
    assert all(isinstance(value, (np.int64, np.float64)) for value in signal_features.values()), "All feature values should be numeric"
    assert all(value >= 0 for value in signal_features.values()), "Feature values should be non-negative"

def test_max_amp():
    # Noisy sine wave with 10 cycles over 1024 samples.
    """
    Test the max_amp feature calculation from a noisy sine wave signal.

    This test verifies that the calculated maximum amplitude from a noisy sine
    wave signal is within the expected range. The expected max_amp value for a
    sine wave is approximately 1, and the test checks whether the calculated
    value deviates from this by less than 0.5.
    """

    signal = np.sin(np.linspace(0, 10 * np.pi, 1024)) + 0.1 * np.random.randn(1024)
    signal_features = create_features(signal)
    assert np.abs(signal_features['max_amp'] - 1) < 0.5 , "max_amp should be within expected range for a sine wave with noise"

def test_sign_changes():
    # Pure sine wave with 10 cycles over 1024 samples.
    """
    Test the sign_changes feature calculation from a pure sine wave signal.

    This test verifies that the calculated number of sign changes from a pure
    sine wave signal is equal to the expected number of cycles. For a pure sine
    wave signal with 10 cycles, the expected number of sign changes is 10.
    """
    signal = np.sin(np.linspace(0, 10 * np.pi, 1024))
    signal_features = create_features(signal)
    assert signal_features['sign_changes'] == 10
    
def test_mean_peak_width():
    # Pure sine wave with 10 cycles over 1024 samples.
    """
    Test the mean_peak_width feature calculation from a pure sine wave signal.

    This test verifies that the calculated mean peak width from a pure sine
    wave signal is within the expected range. The expected mean_peak_width value
    for a pure sine wave signal is approximately 102.3, and the test checks
    whether the calculated value deviates from this by less than 0.1.
    """
    
    signal = np.sin(np.linspace(0, 10 * np.pi, 1024))
    signal_features = create_features(signal)   
    assert np.abs(signal_features['mean_peak_width'] - 102.3) < 0.1, "mean_peak_width should be close to the expected value for a sine wave" 
    
def test_mean_peak_prominence():
    # Noisy sine wave with 10 cycles over 1024 samples.
    """
    Test the mean_peak_prominence feature calculation from a noisy sine wave signal.

    This test verifies that the calculated mean peak prominence from a noisy sine
    wave signal is within the expected range. The expected mean_peak_prominence value
    for a noisy sine wave signal is approximately 2, and the test checks whether the
    calculated value deviates from this by less than 0.5.
    """
    signal = np.sin(np.linspace(0, 10 * np.pi, 1024)) + 0.1 * np.random.randn(1024)
    signal_features = create_features(signal)
    assert np.abs(signal_features['mean_peak_prominence'] - 2) < 0.5, "mean_peak_prominence should be close to the expected value for a sine wave with noise"
